defmodule Liveup.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stages, primary_key: false) do
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:screens, primary_key: false) do
      add :stage_id, references(:stages, column: :id, name: "screens_stage_id_fkey", type: :uuid),
        null: false

      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:events, primary_key: false) do
      add :day_id, references(:days, column: :id, name: "events_day_id_fkey", type: :uuid),
        null: false

      add :time, :time, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:days, primary_key: false) do
      add :day, :date, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:days)

    drop constraint(:events, "events_day_id_fkey")

    drop table(:events)

    drop constraint(:screens, "screens_stage_id_fkey")

    drop table(:screens)

    drop table(:stages)
  end
end